name: orient_ui
description: "A design system for Flutter. Copy and paste widgets."
version: 0.0.4
homepage: https://userorient.com
repository: https://github.com/userorient/orient-ui

exclude:
  - templates/**

executables:
  orient_ui:

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0